# Site settings
title: 
header-img: img/home-bg.png
email: ameecova@yahoo.com
copyright_name: Acova003
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Acova003
learn_profile: Acova003
email_username: ameecova@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
